name: shuju

on:
    push:
        paths:
            - shuju/**
            - .github/workflows/shuju-pull-request.yml
    release:
        types: [published]

jobs:
    build:
        uses: ./.github/workflows/tooling-build.yml
        with:
            service: shuju

    test:
        needs: [build]
        uses: ./.github/workflows/tooling-test.yml
        with:
            service: shuju

    deploy-snapshot:
        needs: [test]
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/workflows/tooling-deploy-snapshot.yml
        with:
            service: shuju
        secrets: inherit

    deploy-prod:
        needs: [test]
        if: ${{ github.event.release }}
        uses: ./.github/workflows/tooling-deploy-prod.yml
        with:
            service: shuju
        secrets: inherit
