name: Build and Release a snapshot CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   uses: actions/cache@v1
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            -   name: Build project
                run: mvn -B compile --file pom.xml

    test:
        needs: build
        runs-on: [ubuntu-latest]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   uses: actions/cache@v1
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            -   name: Test project
                run: mvn -B test --file pom.xml

    check-version-is-snapshot:
        needs: [build, test]
        runs-on: [ubuntu-latest]
        outputs:
            is_snapshot: ${{ steps.check_version.outputs.is_snapshot }}
        steps:
            -   name: Check if that version is a snapshot
                id: check_version
                run: |
                    declare version=$(cat pom.xml  | grep -i "<version>" | head -n 1 | sed -E 's@[ \t]*.version.(.*)./version.@\1@g')
                    if [[ $version == *"SNAPSHOT"* ]]; then echo "::set-output name=is_snapshot::1"; else echo "::set-output name=is_snapshot::0"; fi

    release_snapshot:
        needs: [check-version-is-snapshot]
        if: needs.check-version-is-snapshot.outputs.is_snapshot == 1 # deploy only if the version is a snapshot
        runs-on: [ubuntu-latest]
        steps:
            -   uses: actions/checkout@v2

            -   name: Abort if version isn't snapshot
                run: |
                    declare version=$(cat pom.xml  | grep -i "<version>" | head -n 1 | sed -E 's@[ \t]*.version.(.*)./version.@\1@g')
                    if [[ $version != *"SNAPSHOT"* ]]; then exit 0; else echo "This is a snapshot. All good."; fi

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   uses: actions/cache@v1
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            -   name: Deploy project snapshot
                run: mvn -B clean deploy -Dmaven.test.skip=true --file pom.xml -s my_settings.xml
                env:
                    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
