on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
        secrets:
            OSSRH_USERNAME:
                required: true
            OSSRH_TOKEN:
                required: true
            GPG_PASSPHRASE:
                required: true
            GPG_PRIVATE_KEY:
                required: true

jobs:
    maven-deploy-prod:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: "temurin"

            - uses: actions/cache@v4
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            - name: Installing local dependencies
              run: mvn initialize --file pom.xml --also-make --batch-mode

            - name: Set version
              run: |
                  mvn versions:set -DnewVersion=${{ inputs.version }} --file pom.xml --also-make --batch-mode
                  mvn versions:commit --file pom.xml --also-make --batch-mode

            - name: Setup GPG
              run: |
                  echo "$GPG_PRIVATE_KEY" > private.asc
                  gpg --import --batch private.asc
              env:
                  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

            - name: Deploy project
              run: |
                  export GPG_TTY=$(tty)
                  mvn -U -B clean deploy -P release --file pom.xml -s .mvn/settings.xml --also-make --batch-mode
              env:
                  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
                  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
