name: Release

on:
    push:
        tags:
            - shuju-*

jobs:
    build:
        if: github.event.base_ref == 'refs/heads/master'
        runs-on: [ubuntu-latest]

        steps:
            -   name: Build project
                run: mvn -B clean compile --file pom.xml
            -   name: Test project
                run: mvn -B test --file pom.xml

    release:
        if: github.event.base_ref == 'refs/heads/master'
        runs-on: [ubuntu-latest]

        steps:
            -   name: Create Release
                id: create_release
                uses: actions/create-release@latest
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    release_name: ${{ github.ref }}
                    body: ${{ github.event.head_commit.message }}
                    draft: false
                    prerelease: false

    deploy:
        if: github.event.base_ref == 'refs/heads/master'
        runs-on: [ubuntu-latest]

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
                    server-id: ossrh
                    server-username: MAVEN_USERNAME
                    server-password: MAVEN_PASSWORD
            -   name: Deploy project
                run: mvn -B deploy -Dmaven.test.skip=true --file pom.xml
                env:
                    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
