name: shuju-jackson-json

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - shuju/**
            - .github/workflows/shuju-jackson-json.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: shuju-jackson-json

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: shuju-jackson-json
