name: shuju

on:
    push:
        paths:
            - shuju/**
            - .github/workflows/shuju.yml
    release:
        types: [published]

jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Deploying to production server on branch $GITHUB_REF"
            - run: echo "Deploying to production server on branch $GITHUB_EVENT_NAME"

    build:
        uses: ./.github/workflows/tooling-build.yml
        with:
            service: shuju

    test:
        needs: [build]
        uses: ./.github/workflows/tooling-test.yml
        with:
            service: shuju

    deploy-snapshot:
        needs: [test]
        if: ${{ github.event.push && github.ref == 'main' }}
        uses: ./.github/workflows/tooling-deploy-snapshot.yml
        with:
            service: shuju
        secrets: inherit

    deploy-prod:
        needs: [test]
        if: ${{ github.event.release }}
        uses: ./.github/workflows/tooling-deploy-prod.yml
        with:
            service: shuju
            version: ${{ github.event.release.tag_name }}
        secrets: inherit
