name: shuju

on:
    push:
        branches:
            - '**'
            - "!main"
        paths:
            - shuju/**
            - .github/workflows/shuju.yml

jobs:
    build:
        uses: ./.github/workflows/maven-build.yml
        with:
            service: shuju

    test:
        needs: [build]
        uses: ./.github/workflows/maven-test.yml
        with:
            service: shuju

    deploy-doc:
        needs: [test]
        uses: ./.github/workflows/maven-deploy-doc.yml
