name: shuju-jackson-json

on:
    push:
        paths:
            - shuju/**
            - .github/workflows/shuju-jackson-json.yml
    release:
        types: [published]

jobs:
    build:
        uses: ./.github/workflows/tooling-build.yml
        with:
            service: shuju-jackson-json

    test:
        needs: [build]
        uses: ./.github/workflows/tooling-test.yml
        with:
            service: shuju-jackson-json

    deploy-snapshot:
        needs: [test]
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: ./.github/workflows/tooling-deploy-snapshot.yml
        with:
            service: shuju-jackson-json
        secrets: inherit

    deploy-prod:
        needs: [test]
        if: ${{ github.event_name == 'release' }}
        uses: ./.github/workflows/tooling-deploy-prod.yml
        with:
            service: shuju-jackson-json
            version: ${{ github.event.release.tag_name }}
        secrets: inherit
