name: shuju-monorepo-snapshot

on:
    push:
        branches:
            - "main"

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy-snapshot:
        uses: ./.github/workflows/maven-deploy-snapshot.yml
        secrets: inherit

    deploy-doc:
        needs: [deploy-prod]
        uses: ./.github/workflows/maven-deploy-doc.yml
        with:
            version: 1.44-SNAPSHOT
